bg_project/apps/users/urls.py
from django.urls import path
from django.contrib.auth.views import (LogoutView,
                                       PasswordChangeView,
                                       PasswordChangeDoneView, )

from . import views

urlpatterns = [
    path("login/", views.log_in, name="log_in"),
    path("logout/", LogoutView.as_view(), name="log_out"),
    path("password_change/", PasswordChangeView.as_view(template_name='users/password_change.html'),
         name='password_change'),
    path("password_change_done/", PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
    path("signup/", views.sign_up, name="sign_up"),
    path("signup-confirm/<username>/", views.confirm_signup, name="confirm_sign_up"),
]

bg_project/urls.py
from django.contrib import admin
from django.urls import path, include, register_converter
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.urlpatterns import format_suffix_patterns

from bg_project.apps.boardgames import views as boardgames_views
from bg_project.apps.users import views as user_views
from bg_project.converters import MeetCategory

register_converter(MeetCategory, "meet_category")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('about/', boardgames_views.about, name="about"),
    path('accounts/', include('bg_project.apps.users.urls')),
    path('games/', include('bg_project.apps.boardgames.urls')),
    path('wishlist/', user_views.UsersWishlistView.as_view(), name="wishlist"),
    path('wishlist/<int:user_id>/', user_views.UsersWishlistView.as_view(), name="other_wishlist"),
    path('meet/<int:meet_pk>/', user_views.MeetDetail.as_view(), name="meet_detail"),
    path('meets/manage/<int:meet_id>/', user_views.manage_meeting, name="manage_meeting"),
    path('meets/create/', user_views.create_meet, name="create_meet"),
    path('meets/send-request/<int:meet_id>/', user_views.send_meet_request, name="send_meet_request"),
    path('meets/leave-meet/<int:meet_id>/', user_views.leave_meet_and_cancel_meet_request, name="leave_meet"),
    path('meets/reject-request/<int:meet_id>/<int:user_id>/', user_views.reject_meet_request, name="reject_meet_request"),
    path('meets/confirm-request/<int:meet_id>/<int:user_id>/', user_views.confirm_meet_request, name="confirm_meet_request"),
    path('meets/delete-player/<int:meet_id>/<int:user_id>/', user_views.delete_from_players, name="delete_player"),
    path('meets/<meet_category:category>/', user_views.MeetsListView.as_view(), name="meets"),
    path('add-to-wl/<alias>/', user_views.add_to_remove_from_wishlist, name="wl_adding"),
    path('profile/<int:user_id>/', user_views.ProfileDetailView.as_view(), name="profile_detail"),
    path('profile/edit/<int:user_id>/', user_views.profile_editing, name="profile_editing"),
    path('profile/read-notification/', user_views.read_notification, name="read_all_notification"),
    path('profile/read-notification/<int:not_id>/', user_views.read_notification, name="read_notification"),
    path('profiles-list/', user_views.ProfilesList.as_view(), name="profiles_list"),
    path('friendship-query-send/<int:user_id>/', user_views.send_friendship_query, name="send_friendship_query"),
    path('delete-from-friendlist/<int:user_id>/', user_views.delete_from_friendlist, name="delete_from_friendlist"),
    path('friedship-confirm/<int:user_id>/', user_views.confirm_friendship_query, name="friendship_confirm"),
    path('friendsip-reject/<int:user_id>/', user_views.reject_friendship_query, name="friendship_reject"),
    path('friendsip-cancel-query/<int:user_id>/', user_views.cancel_friendship_query, name="cancel_friendship_query"),
    path('', boardgames_views.index, name="index"),
]

# Добавление urlpatterns для ViewSet BoardGame
urlpatterns += format_suffix_patterns([
    path('api/v0/games/<int:pk>/', boardgames_views.BoardGameViewSet.as_view({'get': 'retrieve'})),
    path('api/v0/games/', boardgames_views.BoardGameViewSet.as_view({'get': 'list'})),
])

# Для доступа к медиа в режиме DEBUG нужно отдельно прописать urls для обработки путей файлов
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('debug-toolbar/', include('debug_toolbar.urls'))]

bg_project/apps/users/models.py
import datetime

from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django.contrib.auth.models import User

from bg_project.apps.boardgames.models import BoardGame
from .services import get_user_profile_media_dir, code_to_confirm_email


class WishList(models.Model):
    """ Модель описывает Вишлист пользователя.
        Создание подвешено через сигнал на создание пользователя. """
    user = models.OneToOneField(to=settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE, )
    games = models.ManyToManyField(BoardGame, related_name="wish_lists")

    def __str__(self):
        return f"Wishlist пользователя {self.user}"


class Profile(models.Model):
    """ Модель описывает профиль пользователя.
        Создание Profile подвешено через сигнал на создание пользователя."""
    GENDERS = [
        ("M", "Мужской"),
        ("Ж", "Женский"),
    ]
    user = models.OneToOneField(to=settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)

    photo = models.ImageField(upload_to=get_user_profile_media_dir, blank=True, null=True)
    email_confirmed = models.BooleanField(default=False)
    email_confirm_code = models.IntegerField(null=True, default=code_to_confirm_email)
    friendlist = models.ManyToManyField(to=settings.AUTH_USER_MODEL,
                                        related_name="friends_profiles")
    location = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    gender = models.CharField(max_length=1, choices=GENDERS, blank=True, null=True)

    def get_absolute_url(self):
        return reverse("profile_detail", kwargs={"user_id": self.user.pk})


class FriendshipQuery(models.Model):
    """ Запрос на добавление пользователя в друзья """
    sender = models.ForeignKey(User, related_name='friendship_queries_from_me', on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name='friendship_queries_to_me', on_delete=models.CASCADE)

    class Meta:
        # Запрет на создание повторяющихся запросов
        constraints = [models.UniqueConstraint(fields=('receiver', 'sender'), name='forbidden_same_friendship_queries')]


class Notification(models.Model):
    """ Уведомление пользователю о каком-либо событии (запрос на добавление в друзья, приглашение во встречу,
        создание встречи другом и т.д."""
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notifications')
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created_at',)


class Meeting(models.Model):
    """ Модель встречи. У встречи может быть только один создатель, 0 и более участников
        Дата и время встречи задается создателем, может быть отредактирована в дальнейшем. """
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_meets')
    players = models.ManyToManyField(User, related_name='meets')
    in_request = models.ManyToManyField(User, related_name='meets_in_request')
    # max_players = models.SmallIntegerField()
    description = models.TextField()
    date = models.DateField()
    time = models.TimeField()
    location = models.CharField(max_length=250)
    notification_task_uuid = models.UUIDField(null=True)

    def get_absolute_url(self):
        return reverse("meet_detail", args=[self.pk])

    @property
    def finished(self):
        """ True, если время игры истекло """
        return self.date < datetime.date.today() or self.time < datetime.datetime.now().time() and self.date == datetime.date.today()

    class Meta:
        ordering = ('date', 'time')

bg_project/apps/users/forms.py
import datetime as dt

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from .models import Profile, Meeting


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(), label="Имя пользователя")
    password = forms.CharField(widget=forms.PasswordInput(), label="Пароль")


class MyUserCreationForms(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(), label="Username")
    email = forms.EmailField(widget=forms.EmailInput(), required=False, label="Email")
    first_name = forms.CharField(required=False, label="Имя")
    last_name = forms.CharField(required=False, label="Фамилия")
    password1 = forms.CharField(widget=forms.PasswordInput(), label="Пароль")
    password2 = forms.CharField(widget=forms.PasswordInput(), label="Повторите пароль")

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')


class ConfirmEmailForm(forms.Form):
    code = forms.IntegerField(widget=forms.TextInput(attrs={"name": "code"}), label="Код подтвержденния")


class ProfileEditForm(forms.Form):
    fname = forms.CharField(required=False, widget=forms.TextInput(), label="Имя")
    lname = forms.CharField(required=False, widget=forms.TextInput(), label="Фамилия")
    location = forms.CharField(required=False, widget=forms.TextInput(), label="Город")
    bio = forms.CharField(required=False, widget=forms.Textarea(attrs={"style": "resize: none"}), label="О себе")
    gender = forms.ChoiceField(required=False, choices=Profile.GENDERS, label="Пол")
    photo = forms.ImageField(required=False, label="Новое фото")

    def clean_fname(self):
        fname = self.cleaned_data.get("fname")
        for digit in "0123456789":
            if digit in fname:
                raise ValidationError("Имя не должно содержать цифры.")
        return fname

    def clean_lname(self):
        lname = self.cleaned_data.get("lname")
        for digit in "0123456789":
            if digit in lname:
                raise ValidationError("Фамилия не должна содержать цифры.")
        return lname


class CreateMeetForm(forms.ModelForm):
    """ Форма для создания встречи.
        Поле creator берется из request.user во view, players вступают во встречу после ее создания"""

    class Meta:
        model = Meeting
        exclude = ('creator', 'players', 'in_request', 'notification_task_uuid')
        labels = {
            'description': 'Описание встречи',
            'date': 'Дата проведения',
            'time': 'Время проведения',
            'location': 'Место проведения',
        }
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'}),
        }

    def clean_date(self):
        if self.cleaned_data['date'] < dt.date.today():
            raise ValidationError('Дата не должна быть прошедшей')
        return self.cleaned_data['date']

    def clean_time(self):
        date = self.cleaned_data.get("date")
        if not date or self.cleaned_data['time'] < dt.datetime.now().time() and \
                date == dt.date.today():
            raise ValidationError('Время и дата не должны быть меньше текущего значения')
        return self.cleaned_data['time']

bg_project/apps/users/templates/users/confirm_email.html
{% extends 'base.html' %}
{% block content %}

    <div style="margin: auto; max-width: 600px">
        <h3 style="text-align: center">Для завершения регистрации введите проверочный код, отправленный на Ваш email</h3>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Ввести код">
        </form>
    </div>
{% endblock %}

bg_project/apps/users/templates/users/login.html
{% extends 'base.html' %}

{% block title %}Вход{% endblock %}

{% block content %}
    <div style="max-width: 600px; margin: auto">
    <h1>Вход</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Вход">
    </form>
    </div>
{% endblock %}

bg_project/apps/users/templates/users/meet_creation.html
{%  extends 'base.html' %}

{% block title %}Создание встречи{% endblock %}

{% block content %}
    <div style="max-width: 600px; margin: auto">
    <h1>Создать новую встречу</h1>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Создать">
        </form>
    </div>
{% endblock %}

bg_project/apps/users/templates/users/meet_detail.html
{% extends "base.html" %}
{% load static users_custom_tags %}

{% block title %}Встреча {{ meet.date|date:"d.m.Y" }}{% endblock %}

{% block css_addition %}
    <link rel="stylesheet" href="{% static "users/css/meet_detail.css" %}">
    <link rel="stylesheet" href="{% static "users/css/friendlist.css" %}">
{% endblock %}

{% block content %}
    <div class="main-container">
        <div class="meet-header">
            <h2>Общее описание</h2>
            <p><b>Создатель встречи:</b> {{ meet.creator.get_full_name|default:meet.creator.username }}
                (<a href="{{ meet.creator.profile.get_absolute_url }}">{{ meet.creator.username }}</a>)</p>
            <p><b>Дата: </b>{{ meet.date|date:"j E Y (l)" }}</p>
            <p><b>Время: </b>{{ meet.time|time:"H:i" }}</p>
            <p><b>Место проведения: </b>{{ meet.location }}</p>
            <p><b>Описание: </b>{{ meet.description }}</p>
            <p><b>Количество участников: </b>{{ meet.players.count }}</p>
            {% if user.is_authenticated %}
                {% if user in meet.players.all %}
                    <a href="{% url "leave_meet" meet.pk %}"><input type="button" value="Покинуть встречу"></a>
                {% elif user in meet.in_request.all %}
                    <a href="{% url "leave_meet" meet.pk %}"><input type="button"
                                                                    value="Отменить запрос на участие"></a>
                {% else %}
                    <a href="{% url "send_meet_request" meet.pk %}"><input type="button"
                                                                    value="Отправить запрос на участие"></a>
                {% endif %}
            {% endif %}
        </div>
        <hr>
        <div class="meet-players">
            <h2>Участники:</h2>
            {% for player in meet.players.all %}
                {% list_item_user player %}
            {% empty %}
                <h2>В этой встрече ещё никто не участвует</h2>
            {% endfor %}
        </div>
    </div>
{% endblock %}

bg_project/apps/users/templates/users/meet_manage.html
{% extends 'base.html' %}
{% load static users_custom_tags %}

{% block title %}Управление встречей{% endblock %}
{% block css_addition %}
    <link rel="stylesheet" href="{% static "users/css/meet_detail.css" %}">
    <link rel="stylesheet" href="{% static "users/css/friendlist.css" %}">
{% endblock %}

{% block content %}
    <div class="main-container">
        <div class="meet-header">
            <h2>Общее описание</h2>
            <p><b>Создатель встречи:</b> {{ meet.creator.get_full_name|default:meet.creator.username }}</p>
            <p><b>Дата: </b>{{ meet.date|date:"j E Y (l)" }}</p>
            <p><b>Время: </b>{{ meet.time|time:"H:i" }}</p>
            <p><b>Место проведения: </b>{{ meet.location }}</p>
            <p><b>Описание: </b>{{ meet.description }}</p>
            <p><b>Количество участников: </b>{{ meet.players.count }}</p>
        </div>
        <hr>
        <div class="meet-players">
            <h2>Заявки на участие: </h2>
            {% for player in meet.in_request.all %}
                {% list_item_user player meet_id=meet.pk button="meet_in_request" %}
            {% empty %}
                <p>Заявок нет</p>
            {% endfor %}
        </div>
        <hr>
        <div class="meet-players">
            <h2>Участники: </h2>
            {% for player in meet.players.all %}
                {% list_item_user player meet_id=meet.pk button="meet_player" %}
            {% empty %}
                <p>Участников нет</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

bg_project/apps/users/templates/users/meets.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Встречи{% endblock %}

{% block css_addition %}
    <link rel="stylesheet" href="{% static 'users/css/meets.css' %}">
    <link rel="stylesheet" href="{% static 'css/paginate.css' %}">
{% endblock %}

{% block content %}

    {% include 'pagination.html' with page=page_obj %}

    <div class="meet-container">
        {% if user.is_authenticated %}
            <div class="meet-sidebar">
                <a href="{% url "meets" "future" %}"><h3>{% if request.resolver_match.kwargs.category == "future" %}--> {% endif %}Ближайшие</h3></a>
                <a href="{% url "meets" "im-creator" %}"><h3>{% if request.resolver_match.kwargs.category == "im-creator" %}--> {% endif %}Созданные мной</h3></a>
                <a href="{% url "meets" "with-my-participation" %}"><h3>{% if request.resolver_match.kwargs.category == "with-my-participation" %}--> {% endif %}С моим участием</h3></a>
                <a href="{% url "meets" "past" %}"><h3>{% if request.resolver_match.kwargs.category == "past" %}--> {% endif %}Прошедшие</h3></a>
                <a href="{% url "create_meet" %}"><input type="button" value="Создать встречу" style="width: 100%"></a>
            </div>
        {% endif %}

        <div class="meet-list-container">
            {% for meet in meets %}
                <div class="meet-list-item">
                    <p><b>Создатель встречи:</b> {{ meet.creator.get_full_name|default:meet.creator.username }}</p>
                    <p><b>Дата: </b>{{ meet.date|date:"j E Y (l)" }}</p>
                    <p><b>Время: </b>{{ meet.time|time:"H:i" }}</p>
                    <p><b>Место проведения: </b>{{ meet.location }}</p>
                    <p><b>Описание: </b>{{ meet.description }}</p>
                    <p><b>Количество участников: </b>{{ meet.players.count }}</p>
                    <p>
                        {% if user == meet.creator %}
                            <a href="{% url "manage_meeting" meet.pk %}">Управлять встречей</a>
                        {% elif user.is_authenticated %}
                            {% if user not in meet.players.all and user not in meet.in_request.all %}
                                <a href="{% url "send_meet_request" meet.pk %}">Подать заявку на участие</a>
                            {% elif user in meet.in_request.all %}
                                <a href="{% url "leave_meet" meet.pk %}">Отменить заявку</a>
                            {% else %}
                                <a href="{% url "leave_meet" meet.pk %}">Покинуть встречу</a>
                            {% endif %}
                        {% endif %}
                    </p>
                    <a href="{% url "meet_detail" meet.pk %}">Страница встречи</a>
                </div>
            {% empty %}
                Нет ни одной предстоящей встречи
            {% endfor %}
        </div>
    </div>
    {% include 'pagination.html' with page=page_obj %}
{% endblock %}

bg_project/apps/users/templates/users/password_change.html
{% extends 'base.html' %}

{% block title %}Смена пароля{% endblock %}

{% block content %}
    <div style="max-width: 600px; margin: auto">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Подтвердить">
        </form>
    </div>
{% endblock %}

bg_project/apps/users/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block title %}Успех{% endblock %}

{% block content %}
    <h1 style="text-align: center"> Пароль успешно изменен! </h1>
{% endblock %}

bg_project/apps/users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block css_addition %}
    <link rel="stylesheet" href="{% static "users/css/profile.css" %}">
    <link rel="stylesheet" href="{% static "users/css/friendlist.css" %}">
{% endblock %}

{% block title %}Профиль{% endblock %}

{% block content %}
    <div class="main-container" style="justify-content: space-around">
        <div class="profile-left {% if not owner %}without-notifications{% endif %}">
            <img src="
                    {% if profile.photo %}{{ profile.photo.url }}{% else %}{% static 'img/no-avatar.png' %}{% endif %}"
                 alt="Ooops" style="max-width: 100%">
            <p><strong>Имя: </strong>{{ profile.user.first_name|default:"Не указано" }}</p>
            <p><strong>Фамилия: </strong>{{ profile.user.last_name|default:"Не указана" }}</p>
            <p><strong>Username: </strong>{{ profile.user.username }}</p>
            <p><strong>Email: </strong>{{ profile.user.email|default:"Не указан" }}</p>
            <p><strong>Пол: </strong>{{ profile.get_gender_display|default:"Не указан" }}</p>
            <p><strong>Город: </strong>{{ profile.location|default:"Не указан" }}</p>
            {% if owner %}
                <a href="{% url "profile_editing" user.id %}"><input type="button" value="Редактировать"></a>
                <a href="{% url "password_change" %}"><input type="button" value="Изменить пароль"></a>
            {% elif user in friendlist %}
                <a href="{% url "other_wishlist" profile.user_id %}"><input type="button" value="Wishlist"></a>
            {% endif %}
        </div>
        <div class="profile-middle {% if not owner %}without-notifications{% endif %}">
            <p><strong>О себе: </strong>{{ profile.bio|default:"Информация не указана" }}</p>
            <hr>
            <a href="{% url "profiles_list" %}"><input type="button" value="Поиск среди пользователей"
                                                       style="font-size: 1rem"></a>
            {% include fl_template_name %}
        </div>
        {% if owner %}
            <div class="profile-right">
            <h3 style="text-align: center">Уведомления</h3>
            <hr>
            <p><strong>Новые уведомления: </strong></p>
            {% for notification in unread_notifications %}
                <div class="profile-notification">
                    <p>{{ forloop.counter }}. {{ notification.message|safe }}</p>
                    <a href="{% url "read_notification" notification.pk %}">В прочитанные </a>
                </div>
            {% empty %}
                Пусто
            {% endfor %}
            {% if unread_notifications %}
                <p><a href="{% url "read_all_notification" %}"> Прочитать все </a></p>
            {% endif %}
            <hr>
            <p><strong>Прочитанные уведомления:</strong></p>
            {% for notification in read_notifications %}
                <div class="profile-notification">
                <p>{{ forloop.counter }}. {{ notification.message|safe }}</p>
                    </div>
                {% empty %}
                    Пусто
                {% endfor %}
            </div>
        {% endif %}
    </div>
{% endblock %}

bg_project/apps/users/templates/users/profile_editing.html
{% extends 'base.html' %}

{% block title %}Профиль{% endblock %}

{% block content %}
    <div style="max-width: 600px; margin: auto">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Сохранить изменения">
        </form>
    </div>
{% endblock %}

bg_project/apps/users/templates/users/profile_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Поиск пользователей{% endblock %}

{% block css_addition %}
    <link rel="stylesheet" href="{% static "users/css/profile_list.css" %}">
    <link rel="stylesheet" href="{% static "css/paginate.css" %}">
{% endblock %}

{% block content %}
    {% include 'pagination.html' with page=page_obj %}

    {% if search_str %}
        <h3 style="text-align: center">Пользователи, которые нашлись по запросу "{{ search_str }}": </h3>
    {% endif %}
    <div class="main-container">
        <div class="profiles-container">
            {% for profile in profiles %}
                <div class="profiles-item">
                    <a href="{% url "profile_detail" profile.user.id %}"><img src="
                            {% if profile.photo %}{{ profile.photo.url }}{% else %}{% static 'img/no-avatar.png' %}{% endif %}"
                                                                              alt="Oooops"></a>
                    <p><strong>Username: </strong>{{ profile.user.username }}</p>
                    <p><strong>Имя: </strong>{{ profile.user.first_name|default:"Не указано" }}</p>
                    <p><strong>Фамилия: </strong>{{ profile.user.last_name|default:"Не указана" }}</p>
                    <p><strong>Пол: </strong>{{ profile.get_gender_display|default:"Не указан" }}</p>
                    <p><strong>Город: </strong>{{ profile.location|default:"Не указан" }}</p>
                    <p class="last">
                        <strong>Bio: </strong>{{ profile.bio|default:"Информация не указана"|truncatewords:10 }}</p>
                    {% if profile in users_friends_profiles %}
                        <a href="{% url "delete_from_friendlist" profile.user.id %}"><input type="button"
                                                                                            value="Удалить из друзей"></a>
                    {% else %}
                        <a href="{% url "send_friendship_query" profile.user.id %}"><input type="button"
                                                                                           value="Добавить в друзья"></a>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
        {% include "sidebar.html" with search_name="search_user" %}
    </div>
    {% include 'pagination.html' with page=page_obj %}
{% endblock %}

bg_project/apps/users/templates/users/sign_up.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
    <div style="max-width: 600px; margin: auto">
    <h1>Регистрация</h1>
    <form action="" method="post">
        {% csrf_token %}
            {{ form.as_p }}
        <input type="submit" value="Регистрация">
    </form>
    </div>
{% endblock %}

bg_project/apps/users/templates/users/user_in_list.html
{% load static %}

<div class="list-item">
    <img src="{% if user_to_print.profile.photo %}
                        {{ user_to_print.profile.photo.url }}
                  {% else %}
                        {% static 'img/no-avatar.png' %}
                  {% endif %}" alt="Oooops" class="miniature">
    <p><a href="{{ user_to_print.profile.get_absolute_url }}">{{ user_to_print.username }}</a>
        ({{ user_to_print.get_full_name }})</p>
    {% if button %}
        {% if button == "delete" %}
            <a href="{% url "delete_from_friendlist" user_to_print.pk %}"><input type="button"
                                                                                 style="font-size: 1rem; padding: 3px"
                                                                                 value="Удалить из друзей"></a>
        {% elif button == "query-from-me" %}
            <a href="{% url "cancel_friendship_query" user_to_print.pk %}"><input type="button"
                                                                                  style="font-size: 1rem; padding: 3px"
                                                                                  value="Отменить заявку"></a>
        {% elif button == "query-to-me" %}
            <a href="{% url "friendship_confirm" user_to_print.pk %}"><input type="button"
                                                                             style="font-size: 1rem; padding: 3px"
                                                                             value="Принять"></a>
            <a href="{% url "friendship_reject" user_to_print.pk %}"><input type="button"
                                                                            style="font-size: 1rem; padding: 3px; margin-left: 10px"
                                                                            value="Отклонить"></a>
        {% elif button == "meet_player" %}
            <a href="{% url "delete_player" meet_id user_to_print.pk %}"><input type="button"
                                                                                style="font-size: 1rem; padding: 3px"
                                                                                value="Удалить из участников"></a>
        {% elif button == "meet_in_request" %}
            <a href="{% url "confirm_meet_request" meet_id user_to_print.pk %}"><input type="button"
                                                                                       style="font-size: 1rem; padding: 3px"
                                                                                       value="Принять"></a>
            <a href="{% url "reject_meet_request" meet_id user_to_print.pk %}"><input type="button"
                                                                                      style="font-size: 1rem;
                                                                                             padding: 3px;
                                                                                             margin-left: 10px"
                                                                                      value="Отклонить"></a>
        {% endif %}
    {% endif %}
</div>

bg_project/apps/users/templates/users/wishlist.html
{% extends 'base.html' %}
{% load static %}
{% load boardgames_custom_filters boardgames_custom_tags%}

{% block title %}
    Wishlist
{% endblock %}

{% block css_addition %}
    <link rel="stylesheet" href="{% static 'boardgames/css/list_view.css' %}">
    <link rel="stylesheet" href="{% static 'css/paginate.css' %}">
{% endblock %}

{% block content %}
    {% if search_str %}
        <h3 style="text-align: center">Вот что нашлось по запросу "{{ search_str }}": </h3>
    {% endif %}
{% include 'pagination.html' with page=page_obj%}
<!-- Вывод всех игр -->
    <div class="main-container">
        <div class="list-container">
            {% if not owner %}
                <h3>Wishlist пользователя {{ user_owner_name }}</h3>
            {% endif %}
            {% for game in wishlist %}
                {% list_item_game button=owner %}
            {% empty %}
                <h1 style="text-align: center">Ваш wishlist пока ещё пустой</h1>
            {% endfor %}
        </div>
        {% include 'sidebar.html' %}
    </div>

<!-- Пагинация -->
{% include 'pagination.html' with page=page_obj%}
{% endblock %}